AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Deploy Ec2 instance hosting minecraft server
Parameters:
  ImageId: 
    Type: AWS::EC2::Image::Id
    Default: "ami-0d5eff06f840b45e9"
  LaunchScript:
    Type: String
    Default: "fresh"
    AllowedValues:
      - "fresh"
      - "current"
  InstanceType:
    Type: String
    Default: "t2.micro"
    AllowedValues:
      - t2.micro
      - t2.medium
      - t2.large
      - t3.xlarge
  AvailabilityZone:
    Type: AWS::EC2::AvailabilityZone::Name
    Default: us-east-1a
  KeyName:
    Type: String
    Default: "Deploy"
Conditions:
  FreshInstall: !Equals
    - !Ref LaunchScript
    - fresh
  CurrentInstall: !Equals
    - !Ref LaunchScript
    - current 
Resources:
  mcServerSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AvailabilityZone
      CidrBlock: "172.31.10.0/24"
      VpcId: "vpc-eef77e93"
      MapPublicIpOnLaunch: false
  mcServerInstanceEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      InstanceId: !Ref mcServerInstance
  mcServerInstanceRole:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles: 
        - GetMCBucket
  mcServerInstance:
    Type: AWS::EC2::Instance
    Condition: FreshInstall
    Properties:
      AvailabilityZone: !Ref AvailabilityZone
      IamInstanceProfile: !Ref mcServerInstanceRole
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroupIds: ["sg-08dafcb6cb310ee66"]
      SubnetId: !Ref mcServerSubnet
      UserData:
        !Base64 |
        #!/bin/bash
        aws s3 cp s3://bootstrap32415/bootstrap.tar /tmp
        tar -xf /tmp/bootstrap.tar -C /tmp
        ./tmp/freshServerInstall.sh
        rm -f /tmp/*.sh
        rm -rf /tmp/*.tar
      Volumes:
      - 
        Device: "/dev/sdh"
        VolumeId: "vol-09bed426a2dccafb1"
  mcServerInstanceCurrent:
    Type: AWS::EC2::Instance
    Condition: CurrentInstall
    Properties:
      AvailabilityZone: !Ref AvailabilityZone
      IamInstanceProfile: !Ref mcServerInstanceRole
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroupIds: ["sg-08dafcb6cb310ee66"]
      SubnetId: !Ref mcServerSubnet
      UserData:
        !Base64 |
        #!/bin/bash
        aws s3 cp s3://bootstrap32415/bootstrap.tar /tmp
        tar -xf /tmp/bootstrap.tar -C /tmp
        ./tmp/currentServerInstall.sh
        rm -f /tmp/*.sh
        rm -rf /tmp/*.tar

      Volumes:
      - 
        Device: "/dev/sdh"
        VolumeId: "vol-09bed426a2dccafb1"
Outputs:
  ServerIP:
    Description: IP address of the server provisioned
    Value: !GetAtt mcServerInstance.PublicIp
    


      
          

